targetTable: s_operation
projectName: core
driver: org.postgresql.Driver
url: jdbc:postgresql://localhost:5432/testdb
# 此处是为了和System.getProperties("username")重复
dbUsername: postgres
password: postgres
author: Li Xiaobing
baseDirPath: 'D:\gitspace\oa_service'
# 需要判重的字
checkRepeatedColumn:
